# GoReleaser configuration for claude-tools-mcp
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    # Run tests before building
    - go test ./...
    # Ensure dependencies are up to date
    - go mod tidy

builds:
  - id: claude-tools-mcp
    main: ./cmd/claude-tools-mcp
    binary: claude-tools-mcp

    # Build for multiple platforms
    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64
      - arm64

    # Environment variables for builds
    env:
      - CGO_ENABLED=0

    # Build flags
    flags:
      - -trimpath

    # Linker flags to reduce binary size and add version info
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    # Archive name template
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    # Files to include in archive
    files:
      - LICENSE*
      - README*
      - CLAUDE.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance Improvements
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  # GitHub release configuration
  github:
    owner: brwse
    name: claude-tools-mcp

  # Draft release for manual review
  draft: false

  # Prerelease detection
  prerelease: auto

  # Release name template
  name_template: "{{.ProjectName}} v{{.Version}}"

  # Footer template for release notes
  footer: |
    ## Installation

    Download the appropriate binary for your platform from the assets below.

    ### Verification

    Verify the download using the checksums.txt file:
    ```bash
    sha256sum -c checksums.txt
    ```
